'use client';

import React from 'react';
import Image from 'next/image';

const SolarBatterySection = () => {
  const containerStyle = {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '80px 20px',
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    alignItems: 'center',
    gap: '40px',
  };

  const headingStyle = {
    fontSize: '36px',
    fontWeight: '700',
    color: '#080808ff', // orange
    marginBottom: '24px',
    lineHeight: 1.2,
  };

  const subheadingStyle = {
    fontSize: '28px',
    fontWeight: '700',
    color: '#111010ff',
    margin: '60px 0 20px',
  };

  const paragraphStyle = {
    fontSize: '16px',
    color: '#333',
    lineHeight: 1.6,
    marginBottom: '16px',
  };

  const linkStyle = {
    color: '#0066cc',
    textDecoration: 'underline',
  };

  return (
    <section>
      <div style={containerStyle}>
        {/* Left Column */}
        <div>
          <h2 style={headingStyle}>Solar battery storage systems</h2>
          <p style={paragraphStyle}>
            Batteries capture and store unused energy generated by your solar panels for you to use when
            the sun isn’t shining. By harnessing natural energy from the sun, it’s a cleaner way to power your
            home and achieve energy independence.
          </p>
          <p style={paragraphStyle}>
            When it comes to renewable energy solutions, solar panels are just the beginning. You can
            maximise your solar savings with a home battery solution to add to an existing solar system or
            include with a new solar installation. Your ability to install a battery may be subject to restrictions
            set by{' '}
            <a href="#" style={linkStyle}>
              the electricity distributor in your area.
            </a>
          </p>
        </div>

        {/* Right Column */}
        <div style={{ textAlign: 'center' }}>
          <Image
            src="/assets/img/shape/sun.png" // replace with your actual path
            alt="Battery Cartoon"
            width={300}
            height={300}
            style={{ objectFit: 'contain' }}
          />
        </div>
      </div>

      {/* Second Section */}
      <div style={containerStyle}>
        {/* Left Column */}
        <div>
          <h3 style={subheadingStyle}>
            How does solar power work when the sun isn’t shining?
          </h3>
        </div>

        {/* Right Column */}
        <div>
          <p style={paragraphStyle}>
            Solar panels require direct sunlight to produce solar energy. You’ll need to add a solar battery
            storage device to your solar system if you’d like to use solar power at night or on overcast days.
          </p>
          <p style={paragraphStyle}>
            Storing solar energy and drawing on your battery’s power until it’s empty is a great way to
            increase your solar self-sufficiency and be less reliant on traditional energy sources.
          </p>
        </div>
      </div>
    </section>
  );
};

export default SolarBatterySection;
